macro(ADD_DEMO _title _dir _option)
  if(${_option})
    message(STATUS "-------------------------------------------------------------------------------")
    message(STATUS "Demo: ${_title}")
    message(STATUS "")
    add_subdirectory(${_dir})
  endif()
endmacro()

macro(START_DEMO_DEPENDENCIES)
  message(STATUS "Configuring Dependencies")
endmacro()

macro(END_DEMO_DEPENDENCIES)
  message(STATUS "")
endmacro()
